name = "A052199"
uuid = "2754adbf-597d-4032-86a7-f89741d07c38"
version = "1.0.3"
authors = ["Jake Ireland <jakewilliami@icloud.com> and contributors"]

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Primes = "0.5.7"
julia = "1.6.7"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "Downloads", "Test"]
